parameters:


services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Netborg\Fediverse\Api\Shared\Domain\CommandBus\CommandHandlerInterface:
      tags: [ !php/const Netborg\Fediverse\Api\Shared\Infrastructure\DependencyInjection\CompilerPass\CommandBusHandlerPass::TAG ]
    Netborg\Fediverse\Api\Shared\Domain\QueryBus\QueryHandlerInterface:
      tags: [ !php/const Netborg\Fediverse\Api\Shared\Infrastructure\DependencyInjection\CompilerPass\QueryBusHandlerPass::TAG ]
    Netborg\Fediverse\Api\WebFingerModule\Application\ResourceResolver\ResourceResolverInterface:
      tags: [ !php/const Netborg\Fediverse\Api\WebFingerModule\Infrastructure\DependencyInjection\CompilerPass\WebFingerResourceResolverPass::TAG ]

  Netborg\Fediverse\Api\WebFingerModule\:
    resource: '../../src/WebFingerModule/'
    exclude:
      - '../../src/WebFingerModule/Application/Exception/'
      - '../../src/WebFingerModule/Application/Model/'
      - '../../src/WebFingerModule/Application/CommandBus/Command/'
      - '../../src/WebFingerModule/Application/QueryBus/Query/'
      - '../../src/WebFingerModule/Domain/Model/'
      - '../../src/WebFingerModule/Infrastructure/DependencyInjection/'
      - '../../src/WebFingerModule/Infrastructure/Entity/'
      - '../../src/WebFingerModule/Infrastructure/Exception/'

  Netborg\Fediverse\Api\WebFingerModule\Application\ResourceResolver\ActorResolver:
    arguments:
      $myDomain: '%domain%'
      $frontendHost: '%frontend_host%'
