league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        enable_password_grant: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available:
            - 'client.register_users'
            - 'user.email'
            - 'user.first_name'
            - 'user.last_name'
            - 'user.posts_read'
            - 'user.posts_write'
        default:
            - 'client.register_users'
            - 'user.email'
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
