league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        enable_password_grant: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available:
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::REGISTER_USERS
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::USER_EMAIL
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::USER_PROFILE
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::USER_POSTS_READ
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::USER_POSTS_WRITE
        default:
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::REGISTER_USERS
            - !php/const Netborg\Fediverse\Api\AuthModule\Domain\Enum\ScopeEnum::USER_EMAIL
    persistence:
        doctrine: ~

#when@test:
#    league_oauth2_server:
#        persistence:
#            in_memory: ~
