nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8080
              description: Local Server
        info:
            title: FediX API Docs
            description: API documentation for FediX backend app.
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc|/doc.json$) # Accepts routes under /api except /api/doc
