parameters:
  password_hashers:
    default:
      algorithm: bcrypt

services:
  password_hasher.factory:
    class: Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
    arguments:
      - '%password_hashers%'

  password_hasher:
    class: Symfony\Component\PasswordHasher\PasswordHasherInterface
    factory: ['@password_hasher.factory', 'getPasswordHasher']
    arguments:
      - default

  Symfony\Component\PasswordHasher\PasswordHasherInterface:
    alias: password_hasher
