version: '2.4'

networks:
  default:
    driver: bridge

services:
  myapp:
    build:
      context: ./.docker/images/myapp
      dockerfile: Dockerfile
    hostname: myapp
    depends_on:
      - postgres
    ports:
      - 8080:80
      - 8443:443
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1
    volumes:
      - ./.docker/volumes/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./:/app
    networks:
      - default

  postgres:
    image: postgres:14.6-alpine
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fedix-ce
      POSTGRES_USER: fedix
      POSTGRES_PASSWORD: fedix123
    volumes:
      - ./.docker/volumes/postgres/data:/var/lib/postgresql/data:rw
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:6
    hostname: pgadmin
    depends_on:
      - postgres
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fedix.com
      PGADMIN_DEFAULT_PASSWORD: fedix123
    networks:
      - default

  redis:
    image: redis:7-alpine
    hostname: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./.docker/volumes/redis/config:/etc/redis
    ports:
      - 6379:6379
    environment:
      REDIS_AUTH: foobar
    networks:
      - default

  mbank:
    image: bbyars/mountebank:2.8.2
    hostname: mbank
    ports:
      - 2525:2525
    networks:
      - default

  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
    networks:
      - default
