jwks_server:
  path: /.well-known/jwks.json
  controller: Netborg\Fediverse\Api\AuthModule\Infrastructure\Controller\JwksController
  methods: [GET]
#  schemes: https

app_login:
  path: /login
  controller: Netborg\Fediverse\Api\AuthModule\Infrastructure\Controller\LoginController::getAction
  methods: [GET, POST]
#  schemes: https

app_logout:
  path: /logout
  methods: [GET]
#  schemes: https
