#oauth2_server:
#    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
#    type: php

oauth2_authorize:
    path: /oauth2/authorize
    controller: 'league.oauth2_server.controller.authorization::indexAction'
    methods: [GET, POST]

oauth2_token:
    path: /api/oauth2/token
    controller: 'league.oauth2_server.controller.token::indexAction'
    methods: [POST]
