#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: Netborg\Fediverse\Api\Controller
#    type: attribute

email_preview:
    path: /email_preview/{email}
    controller: Netborg\Fediverse\Api\Shared\Infrastructure\Controller\MainController::previewEmail
    methods: [GET]
