#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: Netborg\Fediverse\Api\Controller
#    type: attribute

api:
    resource: routes/api.yaml
    prefix: /api
#    schemes: https

webfinger:
    path: /.well-known/webfinger
    controller: Netborg\Fediverse\Api\Controller\WellKnownController::webfinger
    methods: GET
#    schemes: https
