#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: Netborg\Fediverse\Api\Controller
#    type: attribute

api:
    resource: routes/api.yaml
    prefix: /api
#    schemes: https

webfinger:
    resource: routes/webfinger.yaml
#    schemes: https

email_preview:
    path: /email_preview/{email}
    controller: Netborg\Fediverse\Api\Shared\Infrastructure\Controller\MainController::previewEmail
