<?php

declare(strict_types=1);

namespace Netborg\Fediverse\Api\Tests\Integration\API\Users;

use Netborg\Fediverse\Api\Tests\Integration\API\AbstractApiTestCase;
use Netborg\Fediverse\Api\UserModule\Infrastructure\Entity\ActivationLink;
use Netborg\Fediverse\Api\UserModule\Infrastructure\Entity\User;
use Netborg\Fediverse\Api\UserModule\Infrastructure\Repository\ActivationLinkRepository;
use Netborg\Fediverse\Api\UserModule\Infrastructure\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Component\Messenger\Transport\InMemoryTransport;

class LinkActivationTest extends AbstractApiTestCase
{
    private KernelBrowser $client;
    private ActivationLinkRepository $activationLinkRepository;
    private UserRepository $userRepository;

    protected function setUp(): void
    {
        $this->client = self::createClient();
        $this->activationLinkRepository = self::getContainer()->get(ActivationLinkRepository::class);
        $this->userRepository = self::getContainer()->get(UserRepository::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLinkNotFoundCase(): void
    {
        /** @var InMemoryTransport $eventBus */
        $eventBus = self::getContainer()->get('messenger.transport.events');

        $this->client->request('GET', '/api/v1/activation/018655be-5d0d-7b3b-be3f-691582cc8e8f');

        $expected = <<<TXT
{
  "code": 0,
  "error": "Invalid activation link!"
}
TXT;
        $this->assertResponseStatusCodeSame(404);
        $this->assertMatchesPattern($expected, $this->client->getResponse()->getContent());
        $this->assertCount(0, $eventBus->getSent());
    }

    public function testInvalidLinkStructureCase(): void
    {
        /** @var InMemoryTransport $eventBus */
        $eventBus = self::getContainer()->get('messenger.transport.events');

        $this->client->request('GET', '/api/v1/activation/12345678-1234-1234-1234-1234567890ab');

        $expected = <<<TXT
{
  "message": "Invalid data provided.",
  "errors": [
    {
      "property": "activationLink",
      "error": "Invalid activation link"
    }
  ]
}
TXT;
        $this->assertResponseStatusCodeSame(400);
        $this->assertMatchesPattern($expected, $this->client->getResponse()->getContent());
        $this->assertCount(0, $eventBus->getSent());
    }

    public function testExpiredActivationLinkCase(): void
    {
        /** @var InMemoryTransport $eventBus */
        $eventBus = self::getContainer()->get('messenger.transport.events');

        $this->userRepository->save(
            $user = (new User())
                ->setUsername('test')
                ->setEmail('test@example.com')
                ->setPassword('12345678'),
            true
        );

        $this->activationLinkRepository->save(
            $activationLink = (new ActivationLink())
                ->setUser($user)
                ->setExpiresAt((new \DateTimeImmutable())->sub(new \DateInterval('P7D'))),
            true
        );

        $this->client->request('GET', sprintf('/api/v1/activation/%s', $activationLink->getUuid()));

        $expected = <<<TXT
{
  "error": "Activation link has expired!",
  "code": 0
}
TXT;
        $this->assertResponseStatusCodeSame(401);
        $this->assertMatchesPattern($expected, $this->client->getResponse()->getContent());
        $this->assertCount(0, $eventBus->getSent());
    }

    public function testSuccessfulActivationCase(): void
    {
        /** @var InMemoryTransport $eventBus */
        $eventBus = self::getContainer()->get('messenger.transport.events');

        $this->userRepository->save(
            $user = (new User())
                ->setUsername('test')
                ->setEmail('test@example.com')
                ->setPassword('12345678'),
            true
        );

        $this->activationLinkRepository->save(
            $activationLink = (new ActivationLink())
                ->setUser($user)
                ->setExpiresAt((new \DateTimeImmutable())->add(new \DateInterval('PT24H'))),
            true
        );

        $this->client->request('GET', sprintf('/api/v1/activation/%s', $activationLink->getUuid()));

        $expected = <<<TXT
{
  "activation_status": true
}
TXT;
        $this->assertResponseIsSuccessful();
        $this->assertMatchesPattern($expected, $this->client->getResponse()->getContent());
        $this->assertTrue($this->userRepository->findOneById($user->getId())->isActive());
        $this->assertNull($this->activationLinkRepository->findOneByUuid($activationLink->getUuid()));
        $this->assertCount(1, $eventBus->getSent());
    }
}
