api_ap_v1_main:
  path: /
  controller: Netborg\Fediverse\Api\Controller\Api\MainController::main
  methods: GET

api_ap_v1_person:
  prefix: /person
  resource: person/api_ap_v1_person.yaml
#  schemes: https
