<?php

namespace Netborg\Fediverse\Api;

use Netborg\Fediverse\Api\DependencyInjection\CompilerPass\WebFingerResourceResolverPass;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new WebFingerResourceResolverPass());

        parent::build($container); // TODO: Change the autogenerated stub
    }
}
