api_v1_user_get:
  path: '/{identifier}'
  controller: Netborg\Fediverse\Api\Controller\Api\UserController::getAction
  methods: GET
  requirements:
    identifier: '^%username_prefix%[%username_pattern%]+'

api_v1_user_inbox_get:
  path: '/{identifier}/inbox'
  controller: Netborg\Fediverse\Api\Controller\Api\UserInboxController::getAction
  methods: GET
  requirements:
    identifier: '^%username_prefix%[%username_pattern%]+'

api_v1_user_outbox_get:
  path: '/{identifier}/outbox'
  controller: Netborg\Fediverse\Api\Controller\Api\UserOutboxController::getAction
  methods: GET
  requirements:
    identifier: '^%username_prefix%[%username_pattern%]+'

api_v1_user_pub_key_get:
  path: '/{identifier}/pub-key'
  controller: Netborg\Fediverse\Api\Controller\Api\UserPubKeyController::getAction
  methods: GET
  requirements:
    identifier: '^%username_prefix%[%username_pattern%]+'
