api_v1_user_get:
  path: '/user/{identifier}'
  controller: Netborg\Fediverse\Api\UserModule\Infrastructure\Controller\UserController::getAction
  methods: GET
  requirements:
    identifier: '^[%username_pattern%]+'

api_v1_user_create:
  path: '/user'
  controller: Netborg\Fediverse\Api\UserModule\Infrastructure\Controller\UserController::createAction
  methods: POST
  requirements:
    identifier: '^[%username_pattern%]+'

api_v1_user_pub_key_get:
  path: '/user/{identifier}/pub-key'
  controller: Netborg\Fediverse\Api\UserModule\Infrastructure\Controller\UserPubKeyController::getAction
  methods: GET
  requirements:
    identifier: '^[%username_pattern%]+'

api_v1_activation_get:
  path: '/activation/{identifier}'
  controller: Netborg\Fediverse\Api\UserModule\Infrastructure\Controller\ActivationLinkController::getAction
  methods: GET
  requirements:
    identifier: '%uuid_pattern%'
